module ghacc.accel.engine.pac;

import std;
import ghacc.accel.rule;

namespace ghacc::accel {

namespace {

bool is_regex_pattern(std::string_view pattern) {
    if (pattern.starts_with("re:")) return true;
    return pattern.size() >= 2 && pattern.front() == '/' && pattern.back() == '/';
}

std::string js_escape(std::string_view text) {
    std::string out;
    out.reserve(text.size());
    for (char c : text) {
        switch (c) {
            case '\\': out += "\\\\"; break;
            case '"':  out += "\\\""; break;
            default:   out.push_back(c);
        }
    }
    return out;
}

/// Reduce an origin-form/absolute-form target to its path (without query).
std::string_view request_path(std::string_view target) {
    if (const auto scheme = target.find("://"); scheme != std::string_view::npos) {
        const auto slash = target.find('/', scheme + 3);
        target = slash == std::string_view::npos ? std::string_view("/") : target.substr(slash);
    }
    if (const auto query = target.find('?'); query != std::string_view::npos) {
        target = target.substr(0, query);
    }
    return target;
}

} // namespace

std::vector<std::string> pac_patterns(const RuleSet& rules) {
    std::vector<std::string> out;
    for (const auto& pattern : rules.patterns()) {
        if (!is_regex_pattern(pattern)) out.push_back(pattern);
    }
    return out;
}

std::string generate_pac(const RuleSet& rules, const PacOptions& options) {
    const auto patterns = pac_patterns(rules);
    const std::string proxy = options.proxy_host + ":" + std::to_string(options.proxy_port);

    std::string script;
    script += "// Generated by ghacc. Accelerated hosts go through the local proxy.\n";
    script += "function FindProxyForURL(url, host) {\n";
    script += "  host = host.toLowerCase();\n";
    if (!patterns.empty()) {
        script += "  if (";
        bool first = true;
        for (const auto& pattern : patterns) {
            if (!first) script += " ||\n      ";
            first = false;
            script += "shExpMatch(host, \"" + js_escape(pattern) + "\")";
        }
        script += ")\n";
        script += "    return \"PROXY " + proxy + "\";\n";
    }
    script += "  return \"DIRECT\";\n";
    script += "}\n";
    return script;
}

bool is_pac_request(std::string_view target, const PacOptions& options) {
    const std::string_view path = request_path(target);
    return path == options.pac_path || path == "/proxy.pac";
}

} // namespace ghacc::accel
